version: "3"
services:
  redis:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    ports:
      - 6379:6379
      - "${REDIS_PORT_1}:6379"

  python-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT_1}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - redis

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=redis0:redis:6379:0:${REDIS_PASSWORD},redis1:redis:6379:1:${REDIS_PASSWORD},redis2:redis:6379:2:${REDIS_PASSWORD}
      - HTTP_USER=${REDIS_COMMANDER_USER}
      - HTTP_PASSWORD=${REDIS_COMMANDER_PASSWORD}
    ports:
      - "${REDIS_COMMANDER_PORT}:8081"
    depends_on:
      - redis
