version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"