name: DEPLOY API A GATEWAY - Deploy api a gateway to AWS Lambda

on:
  push:
    branches:
      - "release"
    paths:
      - "api-a-front/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActions

      - name: get-caller-identity is allowed to run on role.
        run: aws sts get-caller-identity

      - name: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: lambda update
        run: |
          pip3 install awscli
          cd api-a-gateway && zip -r package.zip ./*
          aws lambda update-function-code --function-name pi-infra-a-gateway --zip-file fileb://package.zip --publish
