name: DEPLOY GH FRONT - Deploy gh front to GitHub Pages

permissions:
  contents: write

on:
  push:
    branches:
      - "release"
    #paths:
    #  - "gh-front/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd ./gh-front
          npm ci

      - name: Build
        run: |
          cd ./gh-front
          npm run build

      - name: Move build to docs
        run: |
          rm -rf ./docs/
          mkdir ./docs
          mv ./gh-front/out/* ./docs/

      # アンダースコアから始まるディレクトリが無視される不具合によってアイコンが404NotFoundになる
      # その不具合を避けるために、`.nojekyll`を追加する
      - name: add .nojekyll
        run: touch ./docs/.nojekyll

      - name: Commit and push
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add -A
          git commit -m "Add dist directory [skip ci]"
          git push
